/*

Welcome to cheat_codes.js! 
The one place where there are no codes and just me venting about how fucking annoying the coding world can be.

First off. Why did no one make a replacement for any `Math.` function for BigInt? I had to make it myself, and that was not fun in the least, I'll tell you that. Why does sqrt look simple yet is so complex? It took me 20 minutes just to figure out how to put it in code. AND THE CODE FOR THAT IS SIMPLE AS SHIT. 
Second. Audio is very finiky. It acts like a spoiled child. It won't tell you shit if you don't have access to F12, and that pains me so much. I have, multiple times, had to add logs into my in-game logs to show me what fucking breaks. It's a pain to do it. 
Third. BigInt is annoying in general. I have to do so much shit just so I can import a save with it. Although BigInt is helpful in some senarios like idle incremental games where you need large amounts, or in this game where your stats can go through the roof because of exponential growth. If you've read this much, you deserve the code luxander Venting Ticket for the codes, but just remove the spaces. 
Fourth. There are so many tiny things that annoy me. One of which being the fact that code, after a bit of time, starts to blur together. That ended up with me trying to unfreeze the screen, while it was already unfrozen. I spent so much time trying to figure out that the problem was me calling 'enablePageClicks()' instead of 'disablePageClicks()' and that caused me to nearly go insane. Fun stuff.
Fifth. WHY THE FUCK DOES `.contains()` NOT EXISTS IN JAVASCRIPT?!
Sixth. Minified code is an actual pain to look at. Like just look at this:
{id:"basic",name:"Basic Loot Box",color:"var(--commonItem)",gemCost:10,rolls:7,pool:[{weight:60,run:()=>{const amt=50n*p.lv;p.gold+=amt;p.totalGold+=amt;return{label:"Gold",value:`+${formatNumber(amt)}g`,color:"var(--gold)"};}},{weight:50,run:()=>{tryAddItem("Apple");return{label:"Item",value:"Apple",color:"var(--commonItem)"};}},{weight:50,run:()=>{tryAddItem("Health Vial");return{label:"Item",value:"Health Vial",color:"var(--commonItem)"};}},{weight:50,run:()=>{tryAddItem("Mana Well");return{label:"Item",value:"Mana Well",color:"var(--commonItem)"};}},{weight:50,run:()=>{tryAddItem("Clarity Tonic");return{label:"Item",value:"Clarity Tonic",color:"var(--commonItem)"};}},{weight:30,run:()=>{tryAddItem("Bottle O' Water");return{label:"Item",value:"Bottle O' Water",color:"var(--commonItem)"};}},{weight:20,run:()=>{const amt=1n*p.lv;p.sp+=amt;return{label:"Skill Points",value:`+${formatNumber(amt)} SP`,color:"var(--exp)"};}},{weight:10,run:()=>{tryAddItem("Blood Stone");return{label:"Item",value:"Blood Stone",color:"var(--rareItem)"};}},]},
TRY READING THAT SHIT. And here's the funny thing, to computers, they're fine with this. They don't care. Yet US. WE get a headache just be fucking LOOKING.
*/